#!/bin/sh
(
    git submodule init
    git submodule update
) > /dev/null
VERSION=$(grep -m 1 VERSION libov/Makefile|sed 's/^.*=//g')
MINORVERSION=$(git rev-list --count release_0_5..HEAD)
COMMIT=$(git rev-parse --short HEAD)
GITSTAT=$(git status --porcelain -uno)
COMMITMOD=$(test -z "${GITSTAT}" || echo "-modified")
echo "ovclient-${VERSION}.${MINORVERSION}-${COMMIT}${COMMITMOD}"
