#!/bin/sh

# deactivate power saving:
for cpu in /sys/devices/system/cpu/cpu[0-9]*; do echo -n performance \
| sudo tee $cpu/cpufreq/scaling_governor; done

## Stop the ntp service
sudo service ntp stop

## Stop the triggerhappy service
sudo service triggerhappy stop

## Stop the dbus service. Warning: this can cause unpredictable behaviour when running a desktop environment on the RPi
sudo service dbus stop

## Stop the console-kit-daemon service. Warning: this can cause unpredictable behaviour when running a desktop environment on the RPi
sudo killall console-kit-daemon

## Stop the polkitd service. Warning: this can cause unpredictable behaviour when running a desktop environment on the RPi
sudo killall polkitd

## Kill the usespace gnome virtual filesystem daemon. Warning: this can cause unpredictable behaviour when running a desktop environment on the RPi
killall gvfsd

## Kill the userspace D-Bus daemon. Warning: this can cause unpredictable behaviour when running a desktop environment on the RPi
killall dbus-daemon

## Kill the userspace dbus-launch daemon. Warning: this can cause unpredictable behaviour when running a desktop environment on the RPi
killall dbus-launch

## Stop all wifi/bluetooth devices
rfkill block all

# if not on overlayfs then update/reinstall:
if (cat /proc/mounts | grep -e " / ")|grep -q -e overlay; then
    # remove old installer scripts:
    rm -f installovclient.sh
    # get the latest installer script:
    wget https://github.com/gisogrimm/ov-client/raw/master/installovclient.sh
    # run installer to update to latest version:
    . installovclient.sh
fi

# start client:
while true; do
    sudo su -l ov -c "ov-client"
    # test for firmware update:
    if test -e ~ov/ov-client.firmwareupdate; then
	# firmware update requested: disable overlayfs and restart
	sudo rm -f ~ov/ov-client.firmwareupdate
	sudo raspi-config nonint disable_overlayfs
	sudo shutdown -r now
    fi
done
