#!/bin/sh
HOMEBREW_REPOSITORY=/opt/homebrew
if test -e /usr/local/Cellar; then
    HOMEBREW_REPOSITORY=/usr/local
fi
DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}:/usr/local/lib"
PATH="${PATH}:/usr/local/bin"
export HOMEBREW_REPOSITORY=$HOMEBREW_REPOSITORY
export HOMEBREW_PREFIX=$HOMEBREW_REPOSITORY
export HOMEBREW_CELLAR=$HOMEBREW_REPOSITORY/Cellar
export PATH="${HOMEBREW_REPOSITORY}/bin:${HOMEBREW_REPOSITORY}/sbin:${PATH}"
DNAME=$(dirname $0)
export RDIR=$($(dirname $0)/ovrealpath $(dirname $0)/../Resources)
export BDIR=$($(dirname $0)/ovrealpath $(dirname $0))
export DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}:${BDIR}/lib"
(
    cd "${TMPDIR}"
    $BDIR/ovbox.bin $*
)
